#ifndef EAX_PRESETS_HPP
#define EAX_PRESETS_HPP

#include "api.h"


// EAX1 =====================================================================

using Eax1ReverbPresets = std::array<EAX_REVERBPROPERTIES, EAX1_ENVIRONMENT_COUNT>;
inline auto constexpr EAX1REVERB_PRESETS = Eax1ReverbPresets{{
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_GENERIC, 0.5F, 1.493F, 0.5F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_PADDEDCELL, 0.25F, 0.1F, 0.0F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_ROOM, 0.417F, 0.4F, 0.666F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_BATHROOM, 0.653F, 1.499F, 0.166F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_LIVINGROOM, 0.208F, 0.478F, 0.0F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_STONEROOM, 0.5F, 2.309F, 0.888F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_AUDITORIUM, 0.403F, 4.279F, 0.5F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_CONCERTHALL, 0.5F, 3.961F, 0.5F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_CAVE, 0.5F, 2.886F, 1.304F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_ARENA, 0.361F, 7.284F, 0.332F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_HANGAR, 0.5F, 10.0F, 0.3F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_CARPETEDHALLWAY, 0.153F, 0.259F, 2.0F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_HALLWAY, 0.361F, 1.493F, 0.0F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_STONECORRIDOR, 0.444F, 2.697F, 0.638F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_ALLEY, 0.25F, 1.752F, 0.776F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_FOREST, 0.111F, 3.145F, 0.472F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_CITY, 0.111F, 2.767F, 0.224F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_MOUNTAINS, 0.194F, 7.841F, 0.472F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_QUARRY, 1.0F, 1.499F, 0.5F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_PLAIN, 0.097F, 2.767F, 0.224F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_PARKINGLOT, 0.208F, 1.652F, 1.5F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_SEWERPIPE, 0.652F, 2.886F, 0.25F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_UNDERWATER, 1.0F, 1.499F, 0.0F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_DRUGGED, 0.875F, 8.392F, 1.388F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_DIZZY, 0.139F, 17.234F, 0.666F},
    EAX_REVERBPROPERTIES{EAX_ENVIRONMENT_PSYCHOTIC, 0.486F, 7.563F, 0.806F},
}};

// EAX2 =====================================================================

inline auto constexpr EAX2REVERB_PRESET_GENERIC = EAX20LISTENERPROPERTIES{
    EAX2LISTENER_DEFAULTROOM,
    EAX2LISTENER_DEFAULTROOMHF,
    EAX2LISTENER_DEFAULTROOMROLLOFFFACTOR,
    EAX2LISTENER_DEFAULTDECAYTIME,
    EAX2LISTENER_DEFAULTDECAYHFRATIO,
    EAX2LISTENER_DEFAULTREFLECTIONS,
    EAX2LISTENER_DEFAULTREFLECTIONSDELAY,
    EAX2LISTENER_DEFAULTREVERB,
    EAX2LISTENER_DEFAULTREVERBDELAY,
    EAX2LISTENER_DEFAULTENVIRONMENT,
    EAX2LISTENER_DEFAULTENVIRONMENTSIZE,
    EAX2LISTENER_DEFAULTENVIRONMENTDIFFUSION,
    EAX2LISTENER_DEFAULTAIRABSORPTIONHF,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_PADDEDCELL = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -6'000_eax_long,
    0.0F,
    0.17F,
    0.1F,
    -1'204_eax_long,
    0.001F,
    207_eax_long,
    0.002F,
    EAX2_ENVIRONMENT_PADDEDCELL,
    1.4F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_ROOM = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -454_eax_long,
    0.0F,
    0.4F,
    0.83F,
    -1'646_eax_long,
    0.002F,
    53_eax_long,
    0.003F,
    EAX2_ENVIRONMENT_ROOM,
    1.9F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_BATHROOM = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -1'200_eax_long,
    0.0F,
    1.49F,
    0.54F,
    -370_eax_long,
    0.007F,
    1'030_eax_long,
    0.011F,
    EAX2_ENVIRONMENT_BATHROOM,
    1.4F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_LIVINGROOM = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -6'000_eax_long,
    0.0F,
    0.5F,
    0.1F,
    -1'376_eax_long,
    0.003F,
    -1'104_eax_long,
    0.004F,
    EAX2_ENVIRONMENT_LIVINGROOM,
    2.5F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_STONEROOM = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -300_eax_long,
    0.0F,
    2.31F,
    0.64F,
    -711_eax_long,
    0.012F,
    83_eax_long,
    0.017F,
    EAX2_ENVIRONMENT_STONEROOM,
    11.6F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_AUDITORIUM = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -476_eax_long,
    0.0F,
    4.32F,
    0.59F,
    -789_eax_long,
    0.02F,
    -289_eax_long,
    0.03F,
    EAX2_ENVIRONMENT_AUDITORIUM,
    21.6F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_CONCERTHALL = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -500_eax_long,
    0.0F,
    3.92F,
    0.7F,
    -1'230_eax_long,
    0.02F,
    -2_eax_long,
    0.029F,
    EAX2_ENVIRONMENT_CONCERTHALL,
    19.6F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_CAVE = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    0_eax_long,
    0.0F,
    2.91F,
    1.3F,
    -602_eax_long,
    0.015F,
    -302_eax_long,
    0.022F,
    EAX2_ENVIRONMENT_CAVE,
    14.6F,
    1.0F,
    -5.0F,
    EAX2LISTENERFLAGS_DECAYTIMESCALE |
        EAX2LISTENERFLAGS_REFLECTIONSSCALE |
        EAX2LISTENERFLAGS_REFLECTIONSDELAYSCALE |
        EAX2LISTENERFLAGS_REVERBSCALE |
        EAX2LISTENERFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAX2REVERB_PRESET_ARENA = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -698_eax_long,
    0.0F,
    7.24F,
    0.33F,
    -1'166_eax_long,
    0.02F,
    16_eax_long,
    0.03F,
    EAX2_ENVIRONMENT_ARENA,
    36.2F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_HANGAR = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -1'000_eax_long,
    0.0F,
    10.05F,
    0.23F,
    -602_eax_long,
    0.02F,
    198_eax_long,
    0.03F,
    EAX2_ENVIRONMENT_HANGAR,
    50.3F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_CARPETTEDHALLWAY = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -4'000_eax_long,
    0.0F,
    0.3F,
    0.1F,
    -1'831_eax_long,
    0.002F,
    -1'630_eax_long,
    0.03F,
    EAX2_ENVIRONMENT_CARPETEDHALLWAY,
    1.9F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_HALLWAY = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -300_eax_long,
    0.0F,
    1.49F,
    0.59F,
    -1'219_eax_long,
    0.007F,
    441_eax_long,
    0.011F,
    EAX2_ENVIRONMENT_HALLWAY,
    1.8F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_STONECORRIDOR = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -237_eax_long,
    0.0F,
    2.7F,
    0.79F,
    -1'214_eax_long,
    0.013F,
    395_eax_long,
    0.02F,
    EAX2_ENVIRONMENT_STONECORRIDOR,
    13.5F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_ALLEY = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -270_eax_long,
    0.0F,
    1.49F,
    0.86F,
    -1'204_eax_long,
    0.007F,
    -4_eax_long,
    0.011F,
    EAX2_ENVIRONMENT_ALLEY,
    7.5F,
    0.3F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_FOREST = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -3'300_eax_long,
    0.0F,
    1.49F,
    0.54F,
    -2'560_eax_long,
    0.162F,
    -229_eax_long,
    0.088F,
    EAX2_ENVIRONMENT_FOREST,
    38.0F,
    0.3F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_CITY = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -800_eax_long,
    0.0F,
    1.49F,
    0.67F,
    -2'273_eax_long,
    0.007F,
    -1'691_eax_long,
    0.011F,
    EAX2_ENVIRONMENT_CITY,
    7.5F,
    0.5F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_MOUNTAINS = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -2'500_eax_long,
    0.0F,
    1.49F,
    0.21F,
    -2'780_eax_long,
    0.3F,
    -1'434_eax_long,
    0.1F,
    EAX2_ENVIRONMENT_MOUNTAINS,
    100.0F,
    0.27F,
    -5.0F,
    EAX2LISTENERFLAGS_DECAYTIMESCALE |
        EAX2LISTENERFLAGS_REFLECTIONSSCALE |
        EAX2LISTENERFLAGS_REFLECTIONSDELAYSCALE |
        EAX2LISTENERFLAGS_REVERBSCALE |
        EAX2LISTENERFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAX2REVERB_PRESET_QUARRY = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -1'000_eax_long,
    0.0F,
    1.49F,
    0.83F,
    -10'000_eax_long,
    0.061F,
    500_eax_long,
    0.025F,
    EAX2_ENVIRONMENT_QUARRY,
    17.5F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_PLAIN = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -2'000_eax_long,
    0.0F,
    1.49F,
    0.5F,
    -2'466_eax_long,
    0.179F,
    -1'926_eax_long,
    0.1F,
    EAX2_ENVIRONMENT_PLAIN,
    42.5F,
    0.21F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_PARKINGLOT = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    0_eax_long,
    0.0F,
    1.65F,
    1.5F,
    -1'363_eax_long,
    0.008F,
    -1'153_eax_long,
    0.012F,
    EAX2_ENVIRONMENT_PARKINGLOT,
    8.3F,
    1.0F,
    -5.0F,
    EAX2LISTENERFLAGS_DECAYTIMESCALE |
        EAX2LISTENERFLAGS_REFLECTIONSSCALE |
        EAX2LISTENERFLAGS_REFLECTIONSDELAYSCALE |
        EAX2LISTENERFLAGS_REVERBSCALE |
        EAX2LISTENERFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAX2REVERB_PRESET_SEWERPIPE = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -1'000_eax_long,
    0.0F,
    2.81F,
    0.14F,
    429_eax_long,
    0.014F,
    1'023_eax_long,
    0.021F,
    EAX2_ENVIRONMENT_SEWERPIPE,
    1.7F,
    0.8F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_UNDERWATER = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -4'000_eax_long,
    0.0F,
    1.49F,
    0.1F,
    -449_eax_long,
    0.007F,
    1'700_eax_long,
    0.011F,
    EAX2_ENVIRONMENT_UNDERWATER,
    1.8F,
    1.0F,
    -5.0F,
    EAX2LISTENER_DEFAULTFLAGS,
};

inline auto constexpr EAX2REVERB_PRESET_DRUGGED = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    0_eax_long,
    0.0F,
    8.39F,
    1.39F,
    -115_eax_long,
    0.002F,
    985_eax_long,
    0.03F,
    EAX2_ENVIRONMENT_DRUGGED,
    1.9F,
    0.5F,
    -5.0F,
    EAX2LISTENERFLAGS_DECAYTIMESCALE |
        EAX2LISTENERFLAGS_REFLECTIONSSCALE |
        EAX2LISTENERFLAGS_REFLECTIONSDELAYSCALE |
        EAX2LISTENERFLAGS_REVERBSCALE |
        EAX2LISTENERFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAX2REVERB_PRESET_DIZZY = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -400_eax_long,
    0.0F,
    17.23F,
    0.56F,
    -1'713_eax_long,
    0.02F,
    -613_eax_long,
    0.03F,
    EAX2_ENVIRONMENT_DIZZY,
    1.8F,
    0.6F,
    -5.0F,
    EAX2LISTENERFLAGS_DECAYTIMESCALE |
        EAX2LISTENERFLAGS_REFLECTIONSSCALE |
        EAX2LISTENERFLAGS_REFLECTIONSDELAYSCALE |
        EAX2LISTENERFLAGS_REVERBSCALE |
        EAX2LISTENERFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAX2REVERB_PRESET_PSYCHOTIC = EAX20LISTENERPROPERTIES{
    -1'000_eax_long,
    -151_eax_long,
    0.0F,
    7.56F,
    0.91F,
    -626_eax_long,
    0.02F,
    774_eax_long,
    0.03F,
    EAX2_ENVIRONMENT_PSYCHOTIC,
    1.0F,
    0.5F,
    -5.0F,
    EAX2LISTENERFLAGS_DECAYTIMESCALE |
        EAX2LISTENERFLAGS_REFLECTIONSSCALE |
        EAX2LISTENERFLAGS_REFLECTIONSDELAYSCALE |
        EAX2LISTENERFLAGS_REVERBSCALE |
        EAX2LISTENERFLAGS_REVERBDELAYSCALE,
};

using Eax2ReverbPresets = std::array<EAX20LISTENERPROPERTIES, EAX2_ENVIRONMENT_COUNT>;
inline auto constexpr EAX2REVERB_PRESETS = Eax2ReverbPresets{{
    EAX2REVERB_PRESET_GENERIC,
    EAX2REVERB_PRESET_PADDEDCELL,
    EAX2REVERB_PRESET_ROOM,
    EAX2REVERB_PRESET_BATHROOM,
    EAX2REVERB_PRESET_LIVINGROOM,
    EAX2REVERB_PRESET_STONEROOM,
    EAX2REVERB_PRESET_AUDITORIUM,
    EAX2REVERB_PRESET_CONCERTHALL,
    EAX2REVERB_PRESET_CAVE,
    EAX2REVERB_PRESET_ARENA,
    EAX2REVERB_PRESET_HANGAR,
    EAX2REVERB_PRESET_CARPETTEDHALLWAY,
    EAX2REVERB_PRESET_HALLWAY,
    EAX2REVERB_PRESET_STONECORRIDOR,
    EAX2REVERB_PRESET_ALLEY,
    EAX2REVERB_PRESET_FOREST,
    EAX2REVERB_PRESET_CITY,
    EAX2REVERB_PRESET_MOUNTAINS,
    EAX2REVERB_PRESET_QUARRY,
    EAX2REVERB_PRESET_PLAIN,
    EAX2REVERB_PRESET_PARKINGLOT,
    EAX2REVERB_PRESET_SEWERPIPE,
    EAX2REVERB_PRESET_UNDERWATER,
    EAX2REVERB_PRESET_DRUGGED,
    EAX2REVERB_PRESET_DIZZY,
    EAX2REVERB_PRESET_PSYCHOTIC,
}};

// EAX3+ ====================================================================

inline auto constexpr EAXREVERB_PRESET_GENERIC = EAXREVERBPROPERTIES{
    EAXREVERB_DEFAULTENVIRONMENT,
    EAXREVERB_DEFAULTENVIRONMENTSIZE,
    EAXREVERB_DEFAULTENVIRONMENTDIFFUSION,
    EAXREVERB_DEFAULTROOM,
    EAXREVERB_DEFAULTROOMHF,
    EAXREVERB_DEFAULTROOMLF,
    EAXREVERB_DEFAULTDECAYTIME,
    EAXREVERB_DEFAULTDECAYHFRATIO,
    EAXREVERB_DEFAULTDECAYLFRATIO,
    EAXREVERB_DEFAULTREFLECTIONS,
    EAXREVERB_DEFAULTREFLECTIONSDELAY,
    EAXREVERB_DEFAULTREFLECTIONSPAN,
    EAXREVERB_DEFAULTREVERB,
    EAXREVERB_DEFAULTREVERBDELAY,
    EAXREVERB_DEFAULTREVERBPAN,
    EAXREVERB_DEFAULTECHOTIME,
    EAXREVERB_DEFAULTECHODEPTH,
    EAXREVERB_DEFAULTMODULATIONTIME,
    EAXREVERB_DEFAULTMODULATIONDEPTH,
    EAXREVERB_DEFAULTAIRABSORPTIONHF,
    EAXREVERB_DEFAULTHFREFERENCE,
    EAXREVERB_DEFAULTLFREFERENCE,
    EAXREVERB_DEFAULTROOMROLLOFFFACTOR,
    EAXREVERB_DEFAULTFLAGS,
};

inline auto constexpr EAXREVERB_PRESET_PADDEDCELL = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_PADDEDCELL,
    1.4F,
    1.0F,
    -1'000_eax_long,
    -6'000_eax_long,
    0_eax_long,
    0.17F,
    0.10F,
    1.0F,
    -1'204_eax_long,
    0.001F,
    EAXVECTOR{},
    207_eax_long,
    0.002F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_ROOM = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_ROOM,
    1.9F,
    1.0F,
    -1'000_eax_long,
    -454_eax_long,
    0_eax_long,
    0.40F,
    0.83F,
    1.0F,
    -1'646_eax_long,
    0.002F,
    EAXVECTOR{},
    53_eax_long,
    0.003F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_BATHROOM = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_BATHROOM,
    1.4F,
    1.0F,
    -1'000_eax_long,
    -1'200_eax_long,
    0_eax_long,
    1.49F,
    0.54F,
    1.0F,
    -370_eax_long,
    0.007F,
    EAXVECTOR{},
    1'030_eax_long,
    0.011F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_LIVINGROOM = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_LIVINGROOM,
    2.5F,
    1.0F,
    -1'000_eax_long,
    -6'000_eax_long,
    0_eax_long,
    0.50F,
    0.10F,
    1.0F,
    -1'376,
    0.003F,
    EAXVECTOR{},
    -1'104_eax_long,
    0.004F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_STONEROOM = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_STONEROOM,
    11.6F,
    1.0F,
    -1'000_eax_long,
    -300_eax_long,
    0_eax_long,
    2.31F,
    0.64F,
    1.0F,
    -711_eax_long,
    0.012F,
    EAXVECTOR{},
    83_eax_long,
    0.017F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_AUDITORIUM = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_AUDITORIUM,
    21.6F,
    1.0F,
    -1'000_eax_long,
    -476_eax_long,
    0_eax_long,
    4.32F,
    0.59F,
    1.0F,
    -789_eax_long,
    0.020F,
    EAXVECTOR{},
    -289_eax_long,
    0.030F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_CONCERTHALL = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_CONCERTHALL,
    19.6F,
    1.0F,
    -1'000_eax_long,
    -500_eax_long,
    0_eax_long,
    3.92F,
    0.70F,
    1.0F,
    -1'230_eax_long,
    0.020F,
    EAXVECTOR{},
    -2_eax_long,
    0.029F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_CAVE = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_CAVE,
    14.6F,
    1.0F,
    -1'000_eax_long,
    0_eax_long,
    0_eax_long,
    2.91F,
    1.30F,
    1.0F,
    -602_eax_long,
    0.015F,
    EAXVECTOR{},
    -302_eax_long,
    0.022F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAXREVERB_PRESET_ARENA = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_ARENA,
    36.2F,
    1.0F,
    -1'000_eax_long,
    -698_eax_long,
    0_eax_long,
    7.24F,
    0.33F,
    1.0F,
    -1'166_eax_long,
    0.020F,
    EAXVECTOR{},
    16_eax_long,
    0.030F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_HANGAR = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_HANGAR,
    50.3F,
    1.0F,
    -1'000_eax_long,
    -1'000_eax_long,
    0_eax_long,
    10.05F,
    0.23F,
    1.0F,
    -602_eax_long,
    0.020F,
    EAXVECTOR{},
    198_eax_long,
    0.030F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_CARPETTEDHALLWAY = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_CARPETEDHALLWAY,
    1.9F,
    1.0F,
    -1'000_eax_long,
    -4'000_eax_long,
    0_eax_long,
    0.30F,
    0.10F,
    1.0F,
    -1'831_eax_long,
    0.002F,
    EAXVECTOR{},
    -1'630_eax_long,
    0.030F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_HALLWAY = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_HALLWAY,
    1.8F,
    1.0F,
    -1'000_eax_long,
    -300_eax_long,
    0_eax_long,
    1.49F,
    0.59F,
    1.0F,
    -1'219_eax_long,
    0.007F,
    EAXVECTOR{},
    441_eax_long,
    0.011F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_STONECORRIDOR = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_STONECORRIDOR,
    13.5F,
    1.0F,
    -1'000_eax_long,
    -237_eax_long,
    0_eax_long,
    2.70F,
    0.79F,
    1.0F,
    -1'214_eax_long,
    0.013F,
    EAXVECTOR{},
    395_eax_long,
    0.020F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_ALLEY = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_ALLEY,
    7.5F,
    0.300F,
    -1'000_eax_long,
    -270_eax_long,
    0_eax_long,
    1.49F,
    0.86F,
    1.0F,
    -1'204_eax_long,
    0.007F,
    EAXVECTOR{},
    -4_eax_long,
    0.011F,
    EAXVECTOR{},
    0.125F,
    0.950F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_FOREST = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_FOREST,
    38.0F,
    0.300F,
    -1'000_eax_long,
    -3'300_eax_long,
    0_eax_long,
    1.49F,
    0.54F,
    1.0F,
    -2'560_eax_long,
    0.162F,
    EAXVECTOR{},
    -229_eax_long,
    0.088F,
    EAXVECTOR{},
    0.125F,
    1.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_CITY = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_CITY,
    7.5F,
    0.500F,
    -1'000_eax_long,
    -800_eax_long,
    0_eax_long,
    1.49F,
    0.67F,
    1.0F,
    -2'273_eax_long,
    0.007F,
    EAXVECTOR{},
    -1'691_eax_long,
    0.011F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_MOUNTAINS = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_MOUNTAINS,
    100.0F,
    0.270F,
    -1'000_eax_long,
    -2'500_eax_long,
    0_eax_long,
    1.49F,
    0.21F,
    1.0F,
    -2'780_eax_long,
    0.300F,
    EAXVECTOR{},
    -1'434_eax_long,
    0.100F,
    EAXVECTOR{},
    0.250F,
    1.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAXREVERB_PRESET_QUARRY = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_QUARRY,
    17.5F,
    1.0F,
    -1'000_eax_long,
    -1'000_eax_long,
    0_eax_long,
    1.49F,
    0.83F,
    1.0F,
    -10'000_eax_long,
    0.061F,
    EAXVECTOR{},
    500_eax_long,
    0.025F,
    EAXVECTOR{},
    0.125F,
    0.700F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_PLAIN = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_PLAIN,
    42.5F,
    0.210F,
    -1'000_eax_long,
    -2'000_eax_long,
    0_eax_long,
    1.49F,
    0.50F,
    1.0F,
    -2'466_eax_long,
    0.179F,
    EAXVECTOR{},
    -1'926_eax_long,
    0.100F,
    EAXVECTOR{},
    0.250F,
    1.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_PARKINGLOT = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_PARKINGLOT,
    8.3F,
    1.0F,
    -1'000_eax_long,
    0_eax_long,
    0_eax_long,
    1.65F,
    1.50F,
    1.0F,
    -1'363_eax_long,
    0.008F,
    EAXVECTOR{},
    -1'153_eax_long,
    0.012F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAXREVERB_PRESET_SEWERPIPE = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_SEWERPIPE,
    1.7F,
    0.800F,
    -1'000_eax_long,
    -1'000_eax_long,
    0_eax_long,
    2.81F,
    0.14F,
    1.0F,
    429_eax_long,
    0.014F,
    EAXVECTOR{},
    1'023_eax_long,
    0.021F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    0.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_UNDERWATER = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_UNDERWATER,
    1.8F,
    1.0F,
    -1'000_eax_long,
    -4'000_eax_long,
    0_eax_long,
    1.49F,
    0.10F,
    1.0F,
    -449_eax_long,
    0.007F,
    EAXVECTOR{},
    1'700_eax_long,
    0.011F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    1.180F,
    0.348F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE
    | EAXREVERBFLAGS_DECAYHFLIMIT,
};

inline auto constexpr EAXREVERB_PRESET_DRUGGED = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_DRUGGED,
    1.9F,
    0.500F,
    -1'000_eax_long,
    0_eax_long,
    0_eax_long,
    8.39F,
    1.39F,
    1.0F,
    -115_eax_long,
    0.002F,
    EAXVECTOR{},
    985_eax_long,
    0.030F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    0.250F,
    1.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAXREVERB_PRESET_DIZZY = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_DIZZY,
    1.8F,
    0.600F,
    -1'000_eax_long,
    -400_eax_long,
    0_eax_long,
    17.23F,
    0.56F,
    1.0F,
    -1'713_eax_long,
    0.020F,
    EAXVECTOR{},
    -613_eax_long,
    0.030F,
    EAXVECTOR{},
    0.250F,
    1.0F,
    0.810F,
    0.310F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE,
};

inline auto constexpr EAXREVERB_PRESET_PSYCHOTIC = EAXREVERBPROPERTIES{
    EAX_ENVIRONMENT_PSYCHOTIC,
    1.0F,
    0.500F,
    -1'000_eax_long,
    -151_eax_long,
    0_eax_long,
    7.56F,
    0.91F,
    1.0F,
    -626_eax_long,
    0.020F,
    EAXVECTOR{},
    774_eax_long,
    0.030F,
    EAXVECTOR{},
    0.250F,
    0.0F,
    4.0F,
    1.0F,
    -5.0F,
    5'000.0F,
    250.0F,
    0.0F,
    EAXREVERBFLAGS_DECAYTIMESCALE
    | EAXREVERBFLAGS_REFLECTIONSSCALE
    | EAXREVERBFLAGS_REFLECTIONSDELAYSCALE
    | EAXREVERBFLAGS_REVERBSCALE
    | EAXREVERBFLAGS_REVERBDELAYSCALE,
};

using EaxReverbPresets = std::array<EAXREVERBPROPERTIES, EAX1_ENVIRONMENT_COUNT>;
inline auto constexpr EAXREVERB_PRESETS = EaxReverbPresets{{
    EAXREVERB_PRESET_GENERIC,
    EAXREVERB_PRESET_PADDEDCELL,
    EAXREVERB_PRESET_ROOM,
    EAXREVERB_PRESET_BATHROOM,
    EAXREVERB_PRESET_LIVINGROOM,
    EAXREVERB_PRESET_STONEROOM,
    EAXREVERB_PRESET_AUDITORIUM,
    EAXREVERB_PRESET_CONCERTHALL,
    EAXREVERB_PRESET_CAVE,
    EAXREVERB_PRESET_ARENA,
    EAXREVERB_PRESET_HANGAR,
    EAXREVERB_PRESET_CARPETTEDHALLWAY,
    EAXREVERB_PRESET_HALLWAY,
    EAXREVERB_PRESET_STONECORRIDOR,
    EAXREVERB_PRESET_ALLEY,
    EAXREVERB_PRESET_FOREST,
    EAXREVERB_PRESET_CITY,
    EAXREVERB_PRESET_MOUNTAINS,
    EAXREVERB_PRESET_QUARRY,
    EAXREVERB_PRESET_PLAIN,
    EAXREVERB_PRESET_PARKINGLOT,
    EAXREVERB_PRESET_SEWERPIPE,
    EAXREVERB_PRESET_UNDERWATER,
    EAXREVERB_PRESET_DRUGGED,
    EAXREVERB_PRESET_DIZZY,
    EAXREVERB_PRESET_PSYCHOTIC,
}};

#endif
