version: 1.20.1.{build}

environment:
    matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        GEN: "Visual Studio 14 2015"
        ARCH: Win32
        CFG: Release
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        GEN: "Visual Studio 14 2015"
        ARCH: x64
        CFG: Release
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        GEN: "Visual Studio 15 2017"
        ARCH: x64
        CFG: Release

install:
    # Remove the VS Xamarin targets to reduce AppVeyor specific noise in build
    # logs.  See also http://help.appveyor.com/discussions/problems/4569
    - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
    - cd build
    - cmake -G "%GEN%" -A %ARCH% -DALSOFT_BUILD_ROUTER=ON -DALSOFT_REQUIRE_WINMM=ON -DALSOFT_REQUIRE_DSOUND=ON -DALSOFT_REQUIRE_WASAPI=ON -DALSOFT_EMBED_HRTF_DATA=YES ..
    - cmake --build . --config %CFG% --clean-first

