SET(CMAKE_SYSTEM_NAME Linux)  # Tell CMake we're cross-compiling

include(CMakeForceCompiler)
# Prefix detection only works with compiler id "GNU"
# CMake will look for prefixed g++, cpp, ld, etc. automatically
CMAKE_FORCE_C_COMPILER(arm-linux-androideabi-gcc GNU)

SET(ANDROID TRUE)
SET(SIZEOF_LONG 4)
SET(SIZEOF_LONG_LONG 8)
SET(HAVE_LIBDL TRUE)
SET(HAVE_LIBM TRUE)
SET(HAVE_ALLOCA_H TRUE)
SET(HAVE_IO_H TRUE)
SET(HAVE_PTHREAD_H TRUE)
SET(HAVE_STRCASECMP TRUE)
SET(HAVE_STRNCASECMP TRUE)
SET(HAVE_GETTIMEOFDAY TRUE)
SET(HAVE_SNPRINTF TRUE)
SET(HAVE_NANOSLEEP TRUE)
SET(HAVE_VISIBILITY_HIDDEN_SWITCH TRUE)
SET(HAVE_ATTRIBUTE_ALIGNED TRUE)
SET(HAVE_ISNAN TRUE)
SET(HAVE_ISFINITE TRUE)
SET(HAVE_PTHREAD TRUE)
SET(HAVE_STAT TRUE)
SET(HAVE_STRTOF TRUE)

# static library
SET(LIBTYPE STATIC)
